# syntax=docker/dockerfile:1

FROM python:3.12-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md ./

RUN pip install --upgrade pip && pip install poetry

# Install dependencies
RUN poetry config virtualenvs.create false \
 && poetry install --with dev --no-root \
 && poetry cache clear pypi --all --no-interaction \
 && rm -rf /tmp/poetry_cache


COPY src/ ./src/
COPY tests/ ./tests/

CMD ["pytest", "--cov=src", "--cov-report=term-missing", "--cov-report=xml", "--cov-fail-under=90"]
