version: '0.1'

services:
  eda:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
    volumes:
      - ./src/app:/app 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  webapp:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - eda
    volumes:
      - ./src/app:/app 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
