[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = "#22C55E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E9F5EC"
textColor = "#1A1A1A"
font = "sans serif"
